### ISSUE TITLE
[BUG][16.0] website: Lỗi khi merge 2 liên hệ

### ISSUE THREAD

**Issue by royle-vietnam** [Viindoo/OpenUpgrade#597]
```
RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
File "/home/tuan/git/odoo16/odoo/http.py", line 1591, in _serve_db
return service_model.retrying(self._serve_ir_http, self.env)
File "/home/tuan/git/odoo16/odoo/service/model.py", line 133, in retrying
result = func()
File "/home/tuan/git/odoo16/odoo/http.py", line 1618, in _serve_ir_http
response = self.dispatcher.dispatch(rule.endpoint, args)
File "/home/tuan/git/odoo16/odoo/http.py", line 1822, in dispatch
result = self.request.registry['ir.http']._dispatch(endpoint)
File "/home/tuan/git/odoo16/addons/website/models/ir_http.py", line 237, in _dispatch
response = super()._dispatch(endpoint)
File "/home/tuan/git/odoo16/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
result = endpoint(**request.params)
File "/home/tuan/git/odoo16/odoo/http.py", line 697, in route_wrapper
result = endpoint(self, *args, **params_ok)
File "/home/tuan/git/odoo16/addons/web/controllers/dataset.py", line 46, in call_button
action = self._call_kw(model, method, args, kwargs)
File "/home/tuan/git/odoo16/addons/web/controllers/dataset.py", line 33, in _call_kw
return call_kw(request.env[model], method, args, kwargs)
File "/home/tuan/git/odoo16/odoo/api.py", line 466, in call_kw
result = _call_kw_multi(method, model, args, kwargs)
File "/home/tuan/git/odoo16/odoo/api.py", line 453, in _call_kw_multi
result = method(recs, *args, **kwargs)
File "/home/tuan/git/odoo16/odoo/addons/base/wizard/base_partner_merge.py", line 633, in action_merge
self._merge(self.partner_ids.ids, self.dst_partner_id)
File "/home/tuan/git/odoo16/odoo/addons/base/wizard/base_partner_merge.py", line 317, in _merge
self._update_foreign_keys(src_partners, dst_partner)
File "/home/tuan/git/odoo16/addons/website/models/base_partner_merge.py", line 27, in _update_foreign_keys
self.env.cr.execute("""
File "/home/tuan/git/odoo16/odoo/sql_db.py", line 321, in execute
res = self._obj.execute(query, params)
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type integer: "06dfa2bc28f3461fbaae5b354eed9e98"

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
at makeErrorFromResponse (http://localhost:8069/web/assets/5837799-1ee0c50/web.assets_backend.min.js:991:163)
at XMLHttpRequest.<anonymous> (http://localhost:8069/web/assets/5837799-1ee0c50/web.assets_backend.min.js:999:13
```
**Giải pháp:**
Bổ sung đoạn code sau vào pre-migration, bởi vì khi thay đổi, Odoo có note ở mô tả pr như vậy, `https://github.com/odoo/odoo/pull/110870`:
```sql
UPDATE website_visitor
SET access_token = partner_id::text
WHERE partner_id IS NOT NULL
```

**Comment by royle-vietnam** [comment]
@duong77476-viindoo em xử luôn cho 16 nhé, làm cho cả OCA nữa

**Comment by daiduongnguyen-odoo** [comment]
> @duong77476-viindoo em xử luôn cho 16 nhé, làm cho cả OCA nữa

Vâng a

**Comment by daiduongnguyen-odoo** [comment]
PR Oca: `https://github.com/OCA/OpenUpgrade/pull/4282`

**Comment by daiduongnguyen-odoo** [comment]
PR liên quan khác https://github.com/Viindoo/odoo-tvtma/pull/1079
